"""
Phase 8.1, evaluation metric #6 (Confidence-calibration spot-check):
does the 0.7 treat_now/monitor cutoff separate real accuracy, and did
fine-tuning on PlantDoc change that -- not just raw accuracy?

Compares the ORIGINAL zero-shot spot-check (Sep 3, docs/evidence/
metric6_perimage_confidence_BEFORE_zeroshot_sep3.json) against a fresh
re-run against the CURRENT fine-tuned checkpoints
(agents/disease/results/plantdoc_perimage_confidence.json, regenerated by
plantdoc_confidence_eval.py in this same session).

Reuses BUCKETS from plantdoc_confidence_analysis.py verbatim (imported,
not redefined) so any change in the accuracy-by-bucket table is
attributable to the model, not to a subtly different analysis method.

CRITICAL METHODOLOGY NOTE, the reason this script exists instead of just
re-running plantdoc_confidence_analysis.py directly: plantdoc_confidence_eval.py
evaluates PlantDoc's train+test folders COMBINED (967 images) -- a valid
design for the ORIGINAL zero-shot check (its own docstring: "no PlantDoc
images used in training for either model"), but INVALID now, since the
current checkpoints WERE fine-tuned on PlantDoc's train split. Re-running
the eval script and quoting its 967-image aggregate accuracy for the new
model would silently mix in 882 train-contaminated images the model has
already seen and fit to. This script restricts the fine-tuned model's
side of the comparison to the SAME 85 test-only images used everywhere
else in this evaluation (docs/evaluation_and_validation.md), so the
before/after comparison stays apples-to-apples.
"""

import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from plantdoc_confidence_analysis import BUCKETS

HERE = os.path.dirname(os.path.abspath(__file__))
OLD_PATH = os.path.join(HERE, "..", "..", "docs", "evidence", "metric6_perimage_confidence_BEFORE_zeroshot_sep3.json")
NEW_PATH = os.path.join(HERE, "results", "plantdoc_perimage_confidence.json")


def bucket_table(records):
    table = []
    for lo, hi, label in BUCKETS:
        bucket = [r for r in records if lo <= r["confidence"] < hi]
        count = len(bucket)
        correct = sum(1 for r in bucket if r["correct"])
        table.append({
            "range": label, "n": count, "correct": correct,
            "accuracy": correct / count if count else None,
        })
    return table


def wilson_ci(correct, n, z=1.96):
    """95% Wilson score confidence interval -- same method used for the
    Potato_healthy n=263 check elsewhere in this evaluation, applied here
    to show explicitly how wide the interval gets at small n."""
    if n == 0:
        return None
    p = correct / n
    denom = 1 + z**2 / n
    center = (p + z**2 / (2 * n)) / denom
    margin = (z * math.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denom
    return {"point_estimate": p, "ci_95_low": max(0.0, center - margin), "ci_95_high": min(1.0, center + margin)}


def cutoff_split(records, cutoff=0.7):
    above = [r for r in records if r["confidence"] >= cutoff]
    below = [r for r in records if r["confidence"] < cutoff]
    above_correct = sum(1 for r in above if r["correct"])
    below_correct = sum(1 for r in below if r["correct"])
    above_acc = above_correct / len(above) if above else None
    below_acc = below_correct / len(below) if below else None
    gap = (above_acc - below_acc) if (above_acc is not None and below_acc is not None) else None
    return {
        "n_above": len(above), "accuracy_above": above_acc,
        "accuracy_above_95_CI": wilson_ci(above_correct, len(above)) if above else None,
        "n_below": len(below), "accuracy_below": below_acc,
        "accuracy_below_95_CI": wilson_ci(below_correct, len(below)) if below else None,
        "gap_above_minus_below": gap,
    }


def main():
    with open(OLD_PATH, encoding="utf-8") as f:
        old_all = json.load(f)
    with open(NEW_PATH, encoding="utf-8") as f:
        new_all = json.load(f)

    old_test = [r for r in old_all if r["image"].startswith("test/")]
    new_test = [r for r in new_all if r["image"].startswith("test/")]
    new_train = [r for r in new_all if r["image"].startswith("train/")]

    assert len(old_all) == len(new_all) == 967, "Image counts differ from the original run -- NOT apples-to-apples, stop and investigate."
    assert len(old_test) == len(new_test), "Test-split sizes differ between old and new per-image files."

    old_cutoff = cutoff_split(old_test)
    new_cutoff = cutoff_split(new_test)
    new_contaminated_cutoff = cutoff_split(new_all)  # explicitly kept, explicitly flagged as invalid below

    old_test_acc = sum(r["correct"] for r in old_test) / len(old_test)
    new_test_acc = sum(r["correct"] for r in new_test) / len(new_test)
    new_train_acc = sum(r["correct"] for r in new_train) / len(new_train)
    new_contaminated_acc = sum(r["correct"] for r in new_all) / len(new_all)

    gap_before = old_cutoff["gap_above_minus_below"]
    gap_after = new_cutoff["gap_above_minus_below"]
    if gap_after > gap_before:
        gap_verdict = f"WIDENED (on the raw numbers): {gap_before:+.4f} -> {gap_after:+.4f}"
    elif gap_after < gap_before:
        gap_verdict = f"SHRANK: {gap_before:+.4f} -> {gap_after:+.4f} -- fine-tuning improved raw accuracy but made the 0.7 cutoff a LESS reliable separator than before."
    else:
        gap_verdict = f"UNCHANGED: {gap_before:+.4f} -> {gap_after:+.4f}"

    SMALL_N_WARN = 10
    small_n_flags = []
    new_above_ci = new_cutoff["accuracy_above_95_CI"]
    if new_cutoff["n_above"] < SMALL_N_WARN:
        ci_txt = (f"95% CI [{new_above_ci['ci_95_low']:.0%}, {new_above_ci['ci_95_high']:.0%}]"
                   if new_above_ci else "CI undefined")
        small_n_flags.append(
            f"AFTER's 'above 0.7' bucket has only n={new_cutoff['n_above']} images "
            f"(75.0% accuracy = 3/4 correct, {ci_txt}). One image flipping "
            f"correct/incorrect moves that accuracy by 25 percentage points. The "
            f"fine-tuned model rarely outputs confidence >=0.7 on this 85-image "
            f"test set at all -- most of its mass sits below the cutoff (n=81). "
            f"The 'gap widened' headline above is technically true but is NOT a "
            f"statistically robust finding at this sample size; report the raw "
            f"numbers, not the verdict, if this is cited."
        )
    if old_cutoff["n_above"] < SMALL_N_WARN or old_cutoff["n_below"] < SMALL_N_WARN:
        small_n_flags.append(
            f"BEFORE's cutoff buckets: n_above={old_cutoff['n_above']}, "
            f"n_below={old_cutoff['n_below']}."
        )
    if small_n_flags:
        gap_verdict += " -- ⚠ SEE small_sample_size_warning IN THIS FILE BEFORE CITING THIS COMPARISON."

    # Single self-contained string, safe to paste verbatim into a slide or
    # report -- the caveat travels WITH the number, not in a separate field
    # that can be dropped when only the headline gets copied.
    citable_summary = (
        f"Confidence-cutoff accuracy gap (>=0.7 vs <0.7): {gap_before:+.2%} before "
        f"fine-tuning -> {gap_after:+.2%} after, on the same 85 held-out PlantDoc "
        f"test images. NOT STATISTICALLY RELIABLE AS STATED: the 'after' side is "
        f"{new_cutoff['accuracy_above']:.0%} accuracy on only n={new_cutoff['n_above']} "
        f"images (95% CI [{new_above_ci['ci_95_low']:.0%}, {new_above_ci['ci_95_high']:.0%}]"
        f" -- consistent with anywhere from roughly a quarter to nearly all of that "
        f"bucket being correct). The more defensible finding is not the gap number: "
        f"fine-tuning shifted the model's confidence distribution down across the "
        f"board ({old_cutoff['n_above']}/85 images scored >=0.7 before vs. "
        f"{new_cutoff['n_above']}/85 after), so DISEASE_CONFIDENCE_CUTOFF=0.7 in "
        f"orchestrator/pipeline.py now routes nearly every real prediction to "
        f"'monitor' rather than 'treat_now' -- an operational question for the "
        f"team, not just a reporting footnote."
    )

    evidence = {
        "metric": "Confidence-calibration spot-check -- is the 0.7 treat_now/monitor cutoff supported by data, and did it change after fine-tuning?",
        "method": (
            "agents/disease/plantdoc_confidence_eval.py re-run against the current "
            "fine-tuned checkpoints (unchanged script, unchanged PLANTDOC_MAP). "
            "Bucket boundaries and 0.7-cutoff logic reused verbatim from "
            "plantdoc_confidence_analysis.py (imported BUCKETS constant, not "
            "redefined) so any change below is attributable to the model, not "
            "the analysis method."
        ),
        "apples_to_apples_check": {
            "old_total_images": len(old_all), "new_total_images": len(new_all),
            "old_test_only_images": len(old_test), "new_test_only_images": len(new_test),
            "same_image_set_confirmed": len(old_all) == len(new_all) == 967 and len(old_test) == len(new_test) == 85,
            "same_missing_folder_caveat": "Tomato two spotted spider mites leaf -- missing from PlantDoc entirely, same in both runs",
        },
        "CRITICAL_METHODOLOGY_FLAG": (
            "The fine-tuned model was trained on PlantDoc's train split. Its "
            "aggregate accuracy over all 967 images (train+test combined) is "
            f"{new_contaminated_acc:.4f} ({sum(r['correct'] for r in new_all)}/967) -- "
            "but 882 of those images were used in fine-tuning and the model has "
            "already fit to them (train-only accuracy: "
            f"{new_train_acc:.4f}). This number is NOT valid for before/after "
            "comparison and is included below only for transparency, clearly "
            "labeled. The only valid comparison uses the 85 held-out test-only "
            "images, which the fine-tuned model never saw during training -- "
            "exactly the same restriction used everywhere else in "
            "docs/evaluation_and_validation.md."
        ),
        "valid_comparison_test_only_n85": {
            "before_zero_shot": {
                "overall_accuracy": old_test_acc,
                "bucket_table": bucket_table(old_test),
                "cutoff_0.7": old_cutoff,
            },
            "after_finetuned": {
                "overall_accuracy": new_test_acc,
                "bucket_table": bucket_table(new_test),
                "cutoff_0.7": new_cutoff,
            },
            "did_fine_tuning_improve_the_CONFIDENCE_SIGNAL_not_just_accuracy": gap_verdict,
            "small_sample_size_warning": small_n_flags if small_n_flags else None,
            "CITABLE_SUMMARY_paste_this_verbatim_into_reports": citable_summary,
            "additional_finding_confidence_distribution_shifted": (
                f"BEFORE: {old_cutoff['n_above']}/85 images ({old_cutoff['n_above']/85:.0%}) "
                f"scored >=0.7 confidence. AFTER: only {new_cutoff['n_above']}/85 "
                f"({new_cutoff['n_above']/85:.0%}). This is the actual reason the "
                "'above 0.7' bucket shrank to n=4 -- the fine-tuned model became "
                "systematically less willing to output high confidence on this "
                "held-out set, not merely more accurate. Operational consequence "
                "for the deployed pipeline: orchestrator/pipeline.py's "
                "DISEASE_CONFIDENCE_CUTOFF=0.7 gates treat_now vs monitor, so "
                "with this model almost every real prediction on unfamiliar "
                "(test-like) photos now routes to 'monitor' rather than "
                "'treat_now' -- consistent with what the confidence-honesty UI "
                "was independently observed showing mostly 'low confidence' "
                "labels during manual testing earlier in this project. Whether "
                "this cutoff is still the right operating point for THIS "
                "model's confidence distribution (as opposed to the zero-shot "
                "model it was never formally chosen against either) is an open "
                "question this spot-check surfaces but does not answer."
            ),
        },
        "INVALID_for_comparison_train_plus_test_combined_n967": {
            "note": "Included ONLY for transparency about what the raw script output looks like -- do not cite this as evidence of calibration change.",
            "before_zero_shot_967img": {
                "overall_accuracy": sum(r["correct"] for r in old_all) / len(old_all),
                "cutoff_0.7": cutoff_split(old_all),
            },
            "after_finetuned_967img_CONTAMINATED": {
                "overall_accuracy": new_contaminated_acc,
                "cutoff_0.7": new_contaminated_cutoff,
                "train_split_accuracy_882img": new_train_acc,
                "test_split_accuracy_85img": new_test_acc,
            },
        },
    }

    print(f"OLD (zero-shot, test-only n=85):  accuracy={old_test_acc:.4f}  "
          f"above-0.7={old_cutoff['accuracy_above']:.4f} (n={old_cutoff['n_above']})  "
          f"below-0.7={old_cutoff['accuracy_below']:.4f} (n={old_cutoff['n_below']})  "
          f"gap={old_cutoff['gap_above_minus_below']:+.4f}")
    print(f"NEW (fine-tuned, test-only n=85): accuracy={new_test_acc:.4f}  "
          f"above-0.7={new_cutoff['accuracy_above']:.4f} (n={new_cutoff['n_above']}, "
          f"95% CI [{new_above_ci['ci_95_low']:.2f}, {new_above_ci['ci_95_high']:.2f}])  "
          f"below-0.7={new_cutoff['accuracy_below']:.4f} (n={new_cutoff['n_below']})  "
          f"gap={new_cutoff['gap_above_minus_below']:+.4f}")
    print(f"\n{gap_verdict}")
    print(f"\n--- Citable summary (paste verbatim, caveat travels with the number) ---")
    print(citable_summary)
    print(f"\n[FLAGGED, not used for comparison] 967-image contaminated accuracy: {new_contaminated_acc:.4f} "
          f"(train-only: {new_train_acc:.4f}, test-only: {new_test_acc:.4f})")

    out_dir = os.path.join(HERE, "..", "..", "docs", "evidence")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "metric6_confidence_calibration_evidence.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(evidence, f, ensure_ascii=False, indent=2)
    print(f"\nSaved -> {out_path}")


if __name__ == "__main__":
    main()
