"""
Phase 8.1, evaluation metric #6 (Confidence-calibration spot-check):
does the 0.7 treat_now/monitor cutoff separate real accuracy, and did
fine-tuning on PlantDoc change that -- not just raw accuracy?

Compares the ORIGINAL zero-shot spot-check (Sep 3, docs/evidence/
metric6_perimage_confidence_BEFORE_zeroshot_sep3.json) against a fresh
re-run against the CURRENT fine-tuned checkpoints
(agents/disease/results/plantdoc_perimage_confidence.json, regenerated by
plantdoc_confidence_eval.py in this same session).

Reuses BUCKETS from plantdoc_confidence_analysis.py verbatim (imported,
not redefined) so any change in the accuracy-by-bucket table is
attributable to the model, not to a subtly different analysis method.

CRITICAL METHODOLOGY NOTE, the reason this script exists instead of just
re-running plantdoc_confidence_analysis.py directly: plantdoc_confidence_eval.py
evaluates PlantDoc's train+test folders COMBINED (967 images) -- a valid
design for the ORIGINAL zero-shot check (its own docstring: "no PlantDoc
images used in training for either model"), but INVALID now, since the
current checkpoints WERE fine-tuned on PlantDoc's train split. Re-running
the eval script and quoting its 967-image aggregate accuracy for the new
model would silently mix in 882 train-contaminated images the model has
already seen and fit to. This script restricts the fine-tuned model's
side of the comparison to the SAME 85 test-only images used everywhere
else in this evaluation (docs/evaluation_and_validation.md), so the
before/after comparison stays apples-to-apples.
"""

import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from plantdoc_confidence_analysis import BUCKETS

HERE = os.path.dirname(os.path.abspath(__file__))
OLD_PATH = os.path.join(HERE, "..", "..", "docs", "evidence", "metric6_perimage_confidence_BEFORE_zeroshot_sep3.json")
NEW_PATH = os.path.join(HERE, "results", "plantdoc_perimage_confidence.json")


def bucket_table(records):
    table = []
    for lo, hi, label in BUCKETS:
        bucket = [r for r in records if lo <= r["confidence"] < hi]
        count = len(bucket)
        correct = sum(1 for r in bucket if r["correct"])
        table.append({
            "range": label, "n": count, "correct": correct,
            "accuracy": correct / count if count else None,
        })
    return table


def wilson_ci(correct, n, z=1.96):
    """95% Wilson score confidence interval -- same method used for the
    Potato_healthy n=263 check elsewhere in this evaluation, applied here
    to show explicitly how wide the interval gets at small n."""
    if n == 0:
        return None
    p = correct / n
    denom = 1 + z**2 / n
    center = (p + z**2 / (2 * n)) / denom
    margin = (z * math.sqrt(p * (1 - p) / n + z**2 / (4 * n**2))) / denom
    return {"point_estimate": p, "ci_95_low": max(0.0, center - margin), "ci_95_high": min(1.0, center + margin)}


def median(values):
    s = sorted(values)
    n = len(s)
    mid = n // 2
    return s[mid] if n % 2 else (s[mid - 1] + s[mid]) / 2


SWEEP_CUTOFFS = [round(0.30 + 0.05 * i, 2) for i in range(9)]  # 0.30 .. 0.70


def cutoff_sweep(test_records):
    """treat_now/monitor split accuracy at each candidate cutoff, on the
    same 85 test-only images used everywhere else in this metric."""
    rows = []
    for c in SWEEP_CUTOFFS:
        treat_now = [r for r in test_records if r["confidence"] >= c]
        monitor = [r for r in test_records if r["confidence"] < c]
        tn_acc = sum(r["correct"] for r in treat_now) / len(treat_now) if treat_now else None
        mon_acc = sum(r["correct"] for r in monitor) / len(monitor) if monitor else None
        rows.append({
            "cutoff": c,
            "treat_now_n": len(treat_now), "treat_now_accuracy": tn_acc,
            "monitor_n": len(monitor), "monitor_accuracy": mon_acc,
        })
    return rows


def ci_overlap_check(test_records, cutoffs=(0.50, 0.55, 0.60)):
    """Wilson 95% CIs for a neighborhood of cutoffs, so overlap (or its
    absence) between adjacent candidates can be read directly, instead of
    comparing point estimates alone -- the check the reviewer asked for
    before treating the sweep's apparent best value as a real optimum."""
    rows = []
    for c in cutoffs:
        b = [r for r in test_records if r["confidence"] >= c]
        k = sum(r["correct"] for r in b)
        n = len(b)
        ci = wilson_ci(k, n) if n else None
        rows.append({
            "cutoff": c, "n": n, "accuracy": k / n if n else None,
            "wilson_95_CI": ci,
        })
    overlapping = True
    intervals = [(r["wilson_95_CI"]["ci_95_low"], r["wilson_95_CI"]["ci_95_high"]) for r in rows if r["wilson_95_CI"]]
    for i in range(len(intervals)):
        for j in range(i + 1, len(intervals)):
            lo1, hi1 = intervals[i]
            lo2, hi2 = intervals[j]
            if hi1 < lo2 or hi2 < lo1:
                overlapping = False
    return rows, overlapping


def bootstrap_stability_check(test_records, n_bootstrap=2000, min_bucket_n=10, seed=42):
    """Resample the 85 test images with replacement n_bootstrap times,
    rerun the full sweep on each resample, and tally how often each
    cutoff comes out as the best-accuracy candidate (restricted to
    candidates with a treat_now bucket of at least min_bucket_n, so a
    lucky n=1 bucket can't 'win' on a fluke). This is the direct test of
    whether the sweep's apparent best cutoff (0.55) reflects a real,
    stable effect or is noise from picking the best of 9 values on one
    85-image split."""
    import random
    rng = random.Random(seed)
    win_counts = {c: 0 for c in SWEEP_CUTOFFS}
    acc_distributions = {c: [] for c in SWEEP_CUTOFFS}
    n = len(test_records)

    for _ in range(n_bootstrap):
        sample = [rng.choice(test_records) for _ in range(n)]
        best_c, best_acc = None, -1
        for c in SWEEP_CUTOFFS:
            bucket = [r for r in sample if r["confidence"] >= c]
            if not bucket:
                continue
            acc = sum(r["correct"] for r in bucket) / len(bucket)
            acc_distributions[c].append(acc)
            if len(bucket) >= min_bucket_n and acc > best_acc:
                best_c, best_acc = c, acc
        if best_c is not None:
            win_counts[best_c] += 1

    rows = []
    for c in SWEEP_CUTOFFS:
        dist = sorted(acc_distributions[c])
        if not dist:
            rows.append({"cutoff": c, "bootstrap_mean_accuracy": None, "bootstrap_95_CI": None,
                          "win_rate": win_counts[c] / n_bootstrap})
            continue
        lo = dist[int(0.025 * len(dist))]
        hi = dist[int(0.975 * len(dist)) - 1]
        rows.append({
            "cutoff": c,
            "bootstrap_mean_accuracy": sum(dist) / len(dist),
            "bootstrap_95_CI": {"low": lo, "high": hi},
            "win_rate": win_counts[c] / n_bootstrap,
        })

    region_win_rate = sum(win_counts[c] for c in SWEEP_CUTOFFS if 0.50 <= c <= 0.65) / n_bootstrap
    return {
        "n_bootstrap": n_bootstrap, "min_bucket_n_to_qualify": min_bucket_n, "seed": seed,
        "per_cutoff": rows,
        "region_0.50_to_0.65_combined_win_rate": region_win_rate,
        "single_best_cutoff_0.55_win_rate": win_counts[0.55] / n_bootstrap,
    }


def cutoff_split(records, cutoff=0.7):
    above = [r for r in records if r["confidence"] >= cutoff]
    below = [r for r in records if r["confidence"] < cutoff]
    above_correct = sum(1 for r in above if r["correct"])
    below_correct = sum(1 for r in below if r["correct"])
    above_acc = above_correct / len(above) if above else None
    below_acc = below_correct / len(below) if below else None
    gap = (above_acc - below_acc) if (above_acc is not None and below_acc is not None) else None
    return {
        "n_above": len(above), "accuracy_above": above_acc,
        "accuracy_above_95_CI": wilson_ci(above_correct, len(above)) if above else None,
        "n_below": len(below), "accuracy_below": below_acc,
        "accuracy_below_95_CI": wilson_ci(below_correct, len(below)) if below else None,
        "gap_above_minus_below": gap,
    }


def main():
    with open(OLD_PATH, encoding="utf-8") as f:
        old_all = json.load(f)
    with open(NEW_PATH, encoding="utf-8") as f:
        new_all = json.load(f)

    old_test = [r for r in old_all if r["image"].startswith("test/")]
    new_test = [r for r in new_all if r["image"].startswith("test/")]
    new_train = [r for r in new_all if r["image"].startswith("train/")]

    assert len(old_all) == len(new_all) == 967, "Image counts differ from the original run -- NOT apples-to-apples, stop and investigate."
    assert len(old_test) == len(new_test), "Test-split sizes differ between old and new per-image files."

    old_cutoff = cutoff_split(old_test)
    new_cutoff = cutoff_split(new_test)
    new_contaminated_cutoff = cutoff_split(new_all)  # explicitly kept, explicitly flagged as invalid below

    # Median-split: answers "should 0.7 still gate treat_now?" with a cutoff
    # sized to what THIS model's actual confidence distribution can support,
    # instead of forcing the old (zero-shot-era) fixed threshold onto a
    # distribution that has since shifted down across the board.
    new_median = median([r["confidence"] for r in new_test])
    new_median_split = cutoff_split(new_test, cutoff=new_median)

    # Cutoff sweep + stability check (Phase 8.1, metric #6 extension,
    # 2026-09-13): the reviewer's sweep request (0.30-0.70, step 0.05)
    # surfaced 0.55 as the apparent best treat_now-bucket accuracy vs the
    # deployed 0.7. Before treating that as a real recommendation, checked
    # whether it survives (a) CI overlap against its neighbors and (b) a
    # bootstrap resample -- selection bias from picking the best of 9 swept
    # values on one 85-image split is a real risk otherwise.
    sweep_rows = cutoff_sweep(new_test)
    ci_overlap_rows, ci_intervals_overlap = ci_overlap_check(new_test, cutoffs=(0.50, 0.55, 0.60))
    bootstrap = bootstrap_stability_check(new_test)

    stability_verdict = (
        "DEFENSIBLE RANGE, NOT A SINGLE POINT. "
        f"0.50/0.55/0.60's Wilson 95% CIs overlap "
        f"{'substantially' if ci_intervals_overlap else 'only partially'} "
        f"(0.50: [{ci_overlap_rows[0]['wilson_95_CI']['ci_95_low']:.1%}, {ci_overlap_rows[0]['wilson_95_CI']['ci_95_high']:.1%}], "
        f"0.55: [{ci_overlap_rows[1]['wilson_95_CI']['ci_95_low']:.1%}, {ci_overlap_rows[1]['wilson_95_CI']['ci_95_high']:.1%}], "
        f"0.60: [{ci_overlap_rows[2]['wilson_95_CI']['ci_95_low']:.1%}, {ci_overlap_rows[2]['wilson_95_CI']['ci_95_high']:.1%}]) "
        f"-- the 85-image test set cannot statistically distinguish these three values from each other. "
        f"Bootstrap resampling (n={bootstrap['n_bootstrap']}) confirms this: 0.55 wins outright in only "
        f"{bootstrap['single_best_cutoff_0.55_win_rate']:.1%} of resamples, but the 0.50-0.65 neighborhood "
        f"wins collectively in {bootstrap['region_0.50_to_0.65_combined_win_rate']:.1%} of resamples -- "
        f"consistent, stable evidence that the TRUE effect lives somewhere in that region, not proof that "
        f"0.55 is the precise optimal value. Reporting '0.55' alone would overclaim precision the evidence "
        f"does not support; reporting '0.50-0.65, centered near 0.55' matches what both checks actually show."
    )

    stability_citable_summary = (
        "[STABILITY CHECK on the metric #6 cutoff sweep, requested before any recommendation was finalized -- "
        "not a change to orchestrator/pipeline.py, which remains at DISEASE_CONFIDENCE_CUTOFF=0.7.] "
        "A sweep of 9 candidate cutoffs (0.30-0.70, step 0.05) on the 85-image PlantDoc test set found 0.55 "
        f"with the highest treat_now-bucket accuracy (75.0%, n=16) vs the deployed 0.7 (75.0%, n=4) -- same "
        "accuracy, far larger sample. Two checks were run to rule out selection bias from sweeping 9 values "
        "and picking the apparent best: (1) Wilson 95% CIs for 0.50 (68.2%, n=22), 0.55 (75.0%, n=16), and "
        "0.60 (72.7%, n=11) overlap almost completely, meaning the data cannot statistically tell these three "
        "apart; (2) a 2,000-iteration bootstrap resample of the 85 images shows 0.55 winning outright in only "
        f"{bootstrap['single_best_cutoff_0.55_win_rate']:.1%} of resamples, while the 0.50-0.65 region wins "
        f"collectively in {bootstrap['region_0.50_to_0.65_combined_win_rate']:.1%} of resamples. Conclusion: "
        "0.50-0.65 is a defensible RANGE where a better-calibrated cutoff than 0.7 likely lives; the evidence "
        "does not support pinning a single 'optimal' value to two decimal places on this sample size. "
        "Recommendation is to document this as an evidence-backed direction for future work, not to hard-code "
        "any specific replacement value into the deployed pipeline at this time."
    )

    old_test_acc = sum(r["correct"] for r in old_test) / len(old_test)
    new_test_acc = sum(r["correct"] for r in new_test) / len(new_test)
    new_train_acc = sum(r["correct"] for r in new_train) / len(new_train)
    new_contaminated_acc = sum(r["correct"] for r in new_all) / len(new_all)

    gap_before = old_cutoff["gap_above_minus_below"]
    gap_after = new_cutoff["gap_above_minus_below"]
    if gap_after > gap_before:
        gap_verdict = f"WIDENED (on the raw numbers): {gap_before:+.4f} -> {gap_after:+.4f}"
    elif gap_after < gap_before:
        gap_verdict = f"SHRANK: {gap_before:+.4f} -> {gap_after:+.4f} -- fine-tuning improved raw accuracy but made the 0.7 cutoff a LESS reliable separator than before."
    else:
        gap_verdict = f"UNCHANGED: {gap_before:+.4f} -> {gap_after:+.4f}"

    SMALL_N_WARN = 10
    small_n_flags = []
    new_above_ci = new_cutoff["accuracy_above_95_CI"]
    if new_cutoff["n_above"] < SMALL_N_WARN:
        ci_txt = (f"95% CI [{new_above_ci['ci_95_low']:.0%}, {new_above_ci['ci_95_high']:.0%}]"
                   if new_above_ci else "CI undefined")
        small_n_flags.append(
            f"AFTER's 'above 0.7' bucket has only n={new_cutoff['n_above']} images "
            f"(75.0% accuracy = 3/4 correct, {ci_txt}). One image flipping "
            f"correct/incorrect moves that accuracy by 25 percentage points. The "
            f"fine-tuned model rarely outputs confidence >=0.7 on this 85-image "
            f"test set at all -- most of its mass sits below the cutoff (n=81). "
            f"The 'gap widened' headline above is technically true but is NOT a "
            f"statistically robust finding at this sample size; report the raw "
            f"numbers, not the verdict, if this is cited."
        )
    if old_cutoff["n_above"] < SMALL_N_WARN or old_cutoff["n_below"] < SMALL_N_WARN:
        small_n_flags.append(
            f"BEFORE's cutoff buckets: n_above={old_cutoff['n_above']}, "
            f"n_below={old_cutoff['n_below']}."
        )
    if small_n_flags:
        gap_verdict += " -- ⚠ SEE small_sample_size_warning IN THIS FILE BEFORE CITING THIS COMPARISON."

    # Single self-contained string, safe to paste verbatim into a slide or
    # report -- the caveat travels WITH the number, not in a separate field
    # that can be dropped when only the headline gets copied. Restructured
    # per review: the distribution shift is the PRIMARY, well-evidenced
    # finding; the before/after gap comparison is demoted to a clearly
    # labeled footnote, since it is not statistically supportable on its own.
    citable_summary = (
        f"[EXPLORATORY ONLY -- not the project's headline Disease Agent result. "
        f"The headline is the zero-shot PlantDoc accuracy (23.45%/28.24%), "
        f"confirmed with Dr. Nagaraju 2026-09-13 for consistency with Phase 1's "
        f"original zero-shot commitment. Everything below describes the "
        f"fine-tuned checkpoint, a secondary result.]\n\n"
        f"PRIMARY FINDING: fine-tuning on PlantDoc shifted the Disease Agent's "
        f"confidence distribution down across the board on the 85 held-out "
        f"PlantDoc test images -- {old_cutoff['n_above']}/85 images scored "
        f">=0.7 confidence on the zero-shot checkpoint "
        f"(stage*_plantvillage_only.pt) vs. only {new_cutoff['n_above']}/85 on "
        f"the deployed fine-tuned checkpoint (stage*_best.pt). Operational "
        f"consequence: orchestrator/pipeline.py's DISEASE_CONFIDENCE_CUTOFF=0.7 "
        f"gates treat_now vs monitor, so with the deployed model almost every "
        f"real prediction on unfamiliar photos now routes to 'monitor' rather "
        f"than 'treat_now' -- consistent with the confidence-honesty UI mostly "
        f"showing 'low confidence' during manual testing. A cutoff placed at "
        f"THIS model's own median confidence ({new_median:.3f}) instead of the "
        f"fixed 0.7 produces a well-populated split (n={new_median_split['n_above']} "
        f"vs n={new_median_split['n_below']}, accuracy {new_median_split['accuracy_above']:.0%} "
        f"vs {new_median_split['accuracy_below']:.0%}) -- whether 0.7 is still the "
        f"right operating point for this model is an open, unresolved question. "
        f"\n\nFOOTNOTE, not a finding: the raw 0.7-cutoff accuracy gap moved "
        f"{gap_before:+.2%} (zero-shot) -> {gap_after:+.2%} (fine-tuned) on the "
        f"same 85 images. This number is NOT statistically reliable and should "
        f"NOT be cited as 'calibration improved' -- the fine-tuned side rests on "
        f"only n={new_cutoff['n_above']} images (95% CI "
        f"[{new_above_ci['ci_95_low']:.0%}, {new_above_ci['ci_95_high']:.0%}]), "
        f"an interval wide enough to be consistent with the true accuracy being "
        f"anywhere from roughly a quarter to nearly all of that bucket. The "
        f"honest state of the evidence is: we cannot currently tell whether the "
        f"0.7 cutoff is better or worse calibrated after fine-tuning, because "
        f"too few predictions cross that threshold to say."
    )

    evidence = {
        "metric": "Confidence-calibration spot-check -- is the 0.7 treat_now/monitor cutoff supported by data, and did it change after fine-tuning?",
        "reporting_status": (
            "EXPLORATORY ONLY -- confirmed with Dr. Nagaraju 2026-09-13 "
            "(see docs/evidence/model_lineage.md's Decision section). The "
            "project's headline Disease Agent accuracy is the ZERO-SHOT "
            "PlantDoc result (model lineage row 2: 23.45%/28.24%), for "
            "methodological consistency with Phase 1's original zero-shot "
            "commitment. The 'after_finetuned' checkpoint in this comparison "
            "(row 5) is a secondary, fine-tuned result -- it is NOT the "
            "reported/deployed-headline finding, and this before/after "
            "comparison should NOT be cited as 'the' calibration result. "
            "Present it, if at all, explicitly labeled exploratory, "
            "alongside that same caveat -- not as a validated improvement."
        ),
        "checkpoints_compared": {
            "before": "checkpoints/stage1_crop_plantvillage_only.pt + stage2_tomato_plantvillage_only.pt + stage2_potato_plantvillage_only.pt -- PlantVillage-only, zero-shot on PlantDoc, never fine-tuned on it. This is model lineage table row 2 -- see docs/evidence/model_lineage.md.",
            "after": "checkpoints/stage1_crop_best.pt + stage2_tomato_best.pt + stage2_potato_best.pt -- fine-tuned on PlantDoc's train split (+ 2 external datasets). This IS the checkpoint orchestrator/pipeline.py loads and deploys right now. Model lineage table row 5.",
            "see_also": "docs/evidence/model_lineage.md for the full checkpoint history and the Phase 1 zero-shot-methodology reconciliation this comparison sits inside of.",
        },
        "method": (
            "agents/disease/plantdoc_confidence_eval.py re-run against the current "
            "fine-tuned checkpoints (unchanged script, unchanged PLANTDOC_MAP). "
            "Bucket boundaries and 0.7-cutoff logic reused verbatim from "
            "plantdoc_confidence_analysis.py (imported BUCKETS constant, not "
            "redefined) so any change below is attributable to the model, not "
            "the analysis method."
        ),
        "apples_to_apples_check": {
            "old_total_images": len(old_all), "new_total_images": len(new_all),
            "old_test_only_images": len(old_test), "new_test_only_images": len(new_test),
            "same_image_set_confirmed": len(old_all) == len(new_all) == 967 and len(old_test) == len(new_test) == 85,
            "same_missing_folder_caveat": "Tomato two spotted spider mites leaf -- missing from PlantDoc entirely, same in both runs",
        },
        "CRITICAL_METHODOLOGY_FLAG": (
            "The fine-tuned model was trained on PlantDoc's train split. Its "
            "aggregate accuracy over all 967 images (train+test combined) is "
            f"{new_contaminated_acc:.4f} ({sum(r['correct'] for r in new_all)}/967) -- "
            "but 882 of those images were used in fine-tuning and the model has "
            "already fit to them (train-only accuracy: "
            f"{new_train_acc:.4f}). This number is NOT valid for before/after "
            "comparison and is included below only for transparency, clearly "
            "labeled. The only valid comparison uses the 85 held-out test-only "
            "images, which the fine-tuned model never saw during training -- "
            "exactly the same restriction used everywhere else in "
            "docs/evaluation_and_validation.md."
        ),
        "valid_comparison_test_only_n85": {
            "before_zero_shot": {
                "overall_accuracy": old_test_acc,
                "bucket_table": bucket_table(old_test),
                "cutoff_0.7": old_cutoff,
            },
            "after_finetuned": {
                "overall_accuracy": new_test_acc,
                "bucket_table": bucket_table(new_test),
                "cutoff_0.7": new_cutoff,
            },
            "did_fine_tuning_improve_the_CONFIDENCE_SIGNAL_not_just_accuracy": gap_verdict,
            "small_sample_size_warning": small_n_flags if small_n_flags else None,
            "median_split_alternative_to_fixed_0.7_cutoff": {
                "note": (
                    "Answers 'should 0.7 still gate treat_now?' with a cutoff sized "
                    "to what the fine-tuned model's ACTUAL confidence distribution "
                    "supports, instead of forcing the old fixed threshold onto a "
                    "distribution that has shifted down."
                ),
                "median_confidence_finetuned_model": new_median,
                "split_at_median": new_median_split,
            },
            "CITABLE_SUMMARY_paste_this_verbatim_into_reports": citable_summary,
            "additional_finding_confidence_distribution_shifted": (
                f"BEFORE: {old_cutoff['n_above']}/85 images ({old_cutoff['n_above']/85:.0%}) "
                f"scored >=0.7 confidence. AFTER: only {new_cutoff['n_above']}/85 "
                f"({new_cutoff['n_above']/85:.0%}). This is the actual reason the "
                "'above 0.7' bucket shrank to n=4 -- the fine-tuned model became "
                "systematically less willing to output high confidence on this "
                "held-out set, not merely more accurate. Operational consequence "
                "for the deployed pipeline: orchestrator/pipeline.py's "
                "DISEASE_CONFIDENCE_CUTOFF=0.7 gates treat_now vs monitor, so "
                "with this model almost every real prediction on unfamiliar "
                "(test-like) photos now routes to 'monitor' rather than "
                "'treat_now' -- consistent with what the confidence-honesty UI "
                "was independently observed showing mostly 'low confidence' "
                "labels during manual testing earlier in this project. Whether "
                "this cutoff is still the right operating point for THIS "
                "model's confidence distribution (as opposed to the zero-shot "
                "model it was never formally chosen against either) is an open "
                "question this spot-check surfaces but does not answer."
            ),
        },
        "cutoff_sweep_and_stability_check_2026-09-13": {
            "context": (
                "Requested after the sweep table was first presented: before treating the sweep's "
                "apparent best value (0.55) as a recommendation, check whether it is a real, stable "
                "finding or an artifact of picking the best of 9 swept values on one 85-image split "
                "(selection bias / multiple comparisons risk). orchestrator/pipeline.py was NOT "
                "changed at any point during this check -- DISEASE_CONFIDENCE_CUTOFF remains 0.7."
            ),
            "sweep_table_0.30_to_0.70_step_0.05": sweep_rows,
            "ci_overlap_check": {
                "method": "Wilson 95% CI for the treat_now bucket at each of the sweep's 3 top-region candidates.",
                "rows": ci_overlap_rows,
                "intervals_overlap": ci_intervals_overlap,
            },
            "bootstrap_stability_check": bootstrap,
            "verdict": stability_verdict,
            "CITABLE_SUMMARY_paste_this_verbatim_into_reports": stability_citable_summary,
            "final_decision_2026-09-13": {
                "status": "DECIDED -- metric #6 is closed",
                "options_considered": {
                    "option_1_chosen": (
                        "Leave DISEASE_CONFIDENCE_CUTOFF at 0.7 in orchestrator/pipeline.py -- no code "
                        "change. Cite the cutoff-sweep + stability-check finding (0.50-0.65 is a "
                        "statistically defensible, likely better-performing range) as a documented "
                        "recommendation for future work, not an applied fix."
                    ),
                    "option_2_rejected": (
                        "Change DISEASE_CONFIDENCE_CUTOFF to a specific value (e.g. 0.55) in "
                        "orchestrator/pipeline.py now, based on the sweep's top result."
                    ),
                },
                "decision": "option_1_chosen",
                "reasoning": (
                    "Deployment risk vs. accuracy gain did not clear the bar this close to the defense. "
                    "The stability check itself is the deciding evidence: the CI-overlap and bootstrap "
                    "results show the gain from moving off 0.7 is real in aggregate (the 0.50-0.65 region "
                    "wins 92.5% of bootstrap resamples) but NOT precisely attributable to any single "
                    "value -- 0.55 alone wins only 50.5% of the time, and its CI overlaps 0.50 and 0.60 "
                    "almost completely. Hard-coding one specific number (e.g. 0.55) into the deployed "
                    "pipeline would misrepresent the evidence as more precise than it is, for a marginal, "
                    "statistically-imprecise accuracy improvement, with real risk of an untested regression "
                    "immediately before the defense. Leaving 0.7 deployed and reporting the range as a "
                    "future-work finding captures the full value of the analysis -- the rigor of running a "
                    "sweep, catching the selection-bias risk, and stability-checking the result -- without "
                    "taking on deployment risk for a change the data can't precisely justify."
                ),
                "pipeline_py_status": (
                    "Confirmed via `git diff -- orchestrator/pipeline.py` (empty) and "
                    "`git log 6f66625..HEAD -- orchestrator/pipeline.py`: DISEASE_CONFIDENCE_CUTOFF has "
                    "remained 0.7 throughout the entire metric #6 investigation (sweep, CI-overlap check, "
                    "bootstrap stability check, and this final decision). The one commit that touched "
                    "pipeline.py during this Phase 8.1 work (3f6e7c0, metric #3's per-stage latency "
                    "instrumentation) is unrelated -- it added a `trace[\"timing\"]` dict and did not "
                    "touch DISEASE_CONFIDENCE_CUTOFF or any cutoff logic. Worth stating explicitly: the "
                    "evaluation process across this entire multi-round statistical vetting did not quietly "
                    "drift into changing deployed system behavior -- every step from the first sweep table "
                    "to this final decision was evidence-gathering only, gated on an explicit human decision."
                ),
            },
        },
        "INVALID_for_comparison_train_plus_test_combined_n967": {
            "note": "Included ONLY for transparency about what the raw script output looks like -- do not cite this as evidence of calibration change.",
            "before_zero_shot_967img": {
                "overall_accuracy": sum(r["correct"] for r in old_all) / len(old_all),
                "cutoff_0.7": cutoff_split(old_all),
            },
            "after_finetuned_967img_CONTAMINATED": {
                "overall_accuracy": new_contaminated_acc,
                "cutoff_0.7": new_contaminated_cutoff,
                "train_split_accuracy_882img": new_train_acc,
                "test_split_accuracy_85img": new_test_acc,
            },
        },
    }

    print(f"OLD (zero-shot, test-only n=85):  accuracy={old_test_acc:.4f}  "
          f"above-0.7={old_cutoff['accuracy_above']:.4f} (n={old_cutoff['n_above']})  "
          f"below-0.7={old_cutoff['accuracy_below']:.4f} (n={old_cutoff['n_below']})  "
          f"gap={old_cutoff['gap_above_minus_below']:+.4f}")
    print(f"NEW (fine-tuned, test-only n=85): accuracy={new_test_acc:.4f}  "
          f"above-0.7={new_cutoff['accuracy_above']:.4f} (n={new_cutoff['n_above']}, "
          f"95% CI [{new_above_ci['ci_95_low']:.2f}, {new_above_ci['ci_95_high']:.2f}])  "
          f"below-0.7={new_cutoff['accuracy_below']:.4f} (n={new_cutoff['n_below']})  "
          f"gap={new_cutoff['gap_above_minus_below']:+.4f}")
    print(f"\n{gap_verdict}")
    print(f"\nMedian-split (cutoff={new_median:.3f}, sized to the fine-tuned model's own distribution):")
    print(f"  above-median: n={new_median_split['n_above']} accuracy={new_median_split['accuracy_above']:.4f}")
    print(f"  below-median: n={new_median_split['n_below']} accuracy={new_median_split['accuracy_below']:.4f}")
    print(f"\n--- Citable summary (paste verbatim, caveat travels with the number) ---")
    print(citable_summary)
    print(f"\n[FLAGGED, not used for comparison] 967-image contaminated accuracy: {new_contaminated_acc:.4f} "
          f"(train-only: {new_train_acc:.4f}, test-only: {new_test_acc:.4f})")

    print(f"\n=== Cutoff sweep (0.30-0.70, step 0.05), test-only n=85 ===")
    print(f"{'Cutoff':<8}{'treat_now n':<14}{'treat_now acc':<16}{'monitor n':<12}{'monitor acc':<12}")
    for row in sweep_rows:
        tn_acc_s = f"{row['treat_now_accuracy']:.1%}" if row['treat_now_accuracy'] is not None else "--"
        mon_acc_s = f"{row['monitor_accuracy']:.1%}" if row['monitor_accuracy'] is not None else "--"
        print(f"{row['cutoff']:<8}{row['treat_now_n']:<14}{tn_acc_s:<16}{row['monitor_n']:<12}{mon_acc_s:<12}")

    print(f"\n=== CI overlap check (0.50 / 0.55 / 0.60) ===")
    for row in ci_overlap_rows:
        ci = row["wilson_95_CI"]
        print(f"  {row['cutoff']}: n={row['n']}, acc={row['accuracy']:.1%}, "
              f"95% CI=[{ci['ci_95_low']:.1%}, {ci['ci_95_high']:.1%}]")
    print(f"  Intervals overlap: {ci_intervals_overlap}")

    print(f"\n=== Bootstrap stability check (n={bootstrap['n_bootstrap']} resamples) ===")
    for row in bootstrap["per_cutoff"]:
        print(f"  {row['cutoff']}: win_rate={row['win_rate']:.1%}")
    print(f"  0.55 win rate: {bootstrap['single_best_cutoff_0.55_win_rate']:.1%}")
    print(f"  0.50-0.65 region combined win rate: {bootstrap['region_0.50_to_0.65_combined_win_rate']:.1%}")

    print(f"\n--- Stability verdict ---")
    print(stability_verdict)
    print(f"\n--- Stability check citable summary ---")
    print(stability_citable_summary)
    print(f"\n--- Final decision (2026-09-13) ---")
    print("Option 1 CHOSEN: leave DISEASE_CONFIDENCE_CUTOFF at 0.7, cite range as future-work recommendation.")
    print(f"pipeline.py DISEASE_CONFIDENCE_CUTOFF confirmed unchanged: 0.7 (see final_decision_2026-09-13.pipeline_py_status in JSON)")

    out_dir = os.path.join(HERE, "..", "..", "docs", "evidence")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "metric6_confidence_calibration_evidence.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(evidence, f, ensure_ascii=False, indent=2)
    print(f"\nSaved -> {out_path}")


if __name__ == "__main__":
    main()
